### ISSUE TITLE
Streets - cost per mile

### ISSUE THREAD

**Issue by omarpassons** [cityofsandiego/streetsSD#10]
Hey gang - I have no idea how to do this, so I hope this is right.  There are a few things that would strengthen the very cool new tool.  Here goes:

1. Add cost/mile of the three types of street repairs so people quickly know some context.

2. Link back to procurement so that the contract can be accessed for things like project cost

3. Make available by neighborhood, census tract, zip, planning district. I think these cuts will make the data valuable for non profit grant writing purposes as well as for nerds like me to just dork out on.

4.  If our pavement management system also has the type of various roads, would be good to be able to visualize how much asphalt versus concrete exists

5.  Side-by-side - If possible, add to user interface options to allow side by side comparisons of maps.  Switching back and forth is hard to evaluate the differences

Thanks!

**Comment by MrMaksimize** [comment]
Hey @omarpassons!  Thanks for doing this!  I've broken this issue down into more granular tasks.  (https://github.com/cityofsandiego/streetsSD/issues)  

As we get more feedback from other users and discover additional bugs, we'll be putting them into the issue queue.  

Sometime in the near future, when we do another sprint on this tool, we'll prioritize the tasks based on what we can get done + what is the most critical and tackle those first.  

Also, the beauty of Github is that anyone can fork this, contribute code and we can merge it into the existing codebase.  So if you or someone else you know who is a developer wanted to go, implement #14 for example, we'd be able to merge it into the codebase.  Open source for the win!

Meanwhile I'll close this large one, since it's redundant with the more granular ones.

Thanks so much for doing this -- I like some of your suggestions!
